### ISSUE TITLE
How To Use

### ISSUE THREAD

**Issue by hosttcp** [TheCarpetMerchant/hive_multiisolate#1]
Hi, tell me how I can use this library?

**Comment by TheCarpetMerchant** [comment]
Add it to your project using a git reference, then you can use the HiveMultiIsolateBox class instead of a regular Hive box.
Every time you call something from it, it will open the box, do what your asked and close the box.
Hive locks the file as long as the box is used, so if the file is locked this class will retry in 100 milliseconds.

But this is a hack, only use it as a last resort !

**Comment by hosttcp** [comment]
Thanks for your work, I did.
